# Generated by Django 4.0 on 2021-12-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.TextField(default='Java'),
            preserve_default=False,
        ),
    ]
