# Generated by Django 4.1 on 2022-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
