# Generated by Django 3.2.8 on 2022-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='language',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
