# Generated by Django 4.1 on 2022-09-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langrec', '0002_auto_20220107_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='url',
            field=models.URLField(default='/'),
        ),
    ]
