databases:
  - name: portfolio
    databaseName: portfolio
    user: portfolio_user
    ipAllowList: []
    plan: free
    region: ohio
    postgresMajorVersion: 14

services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Portfolio.asgi:application -w 4 -k uvicorn.workers.UvicornWorker"
    plan: starter
    region: ohio
    healthCheckPath: /health/?format=json
    domains:
      - bilalmadi.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEVELOPMENT_MODE
        value: false
      - key: SERVE_MEDIA
        value: true
      - key: ALLOWED_HOSTS
        value: bilalmadi.com,portfolio-5656.onrender.com